spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  application:
    name: cotacao  sql:    init:      mode: always      continue-on-error: true      data-locations:      - classpath:data.sql      platform: postgresql
    
server:
  port: 8081
  error:
    include-stacktrace: on-param